name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Build Backend Docker Image
    - name: Build Backend Docker Image
      run: |
        docker build \
          -t taskflow-backend:test \
          ./taskflow-3tierApp/backend

    # Build Frontend Docker Image
    - name: Build Frontend Docker Image
      run: |
        docker build \
          -t taskflow-frontend:test \
          ./*/frontend

    # Optional: List Docker Images (Verification)
    - name: Verify Docker Images
      run: docker images
